##Default Server Config
nick: k1llerbot
OAuth: oauth:sgmrecmyrofj7xgpbypbr6da3jkzdq

autoJoinChannel: k1llerk4se

serverHost: irc.twitch.tv
serverPort: 6667

useSQLite: false

MySQLHost: localhost
MySQLTable: users
MySQLUserName:
MySQLPassword: 